### ISSUE TITLE
Errors building on Linux

### ISSUE THREAD

**Issue by tank-trax** [Mrugalla/Manta#3]
Debian 11

```
Compiling MIDICCMonitor.cpp
In file included from ../../Source/gui/../Processor.h:15,
                 from ../../Source/gui/Using.h:11,
                 from ../../Source/gui/Utils.h:2,
                 from ../../Source/gui/Comp.h:2,
                 from ../../Source/gui/FilterResponseGraph.h:2,
                 from ../../Source/gui/FilterResponseGraph.cpp:1:
../../Source/gui/../audio/Manta.h: In member function ‘void audio::Manta::Lane::operator()(float**, int, int, bool, float, float, int, float, float, float, float, float, float, float, float, const int*, const audio::XenManager&)’:
../../Source/gui/../audio/Manta.h:237:5: error: no match for call to ‘(audio::Manta::Filter) (float* const*&, float**&, int&, int&, float* const&, float* const&, int&)’
  237 |     );
      |     ^
../../Source/gui/../audio/Manta.h:31:9: note: candidate: ‘void audio::Manta::Filter::operator()(float**, float**, int, int, float*, float*, int)’ (near match)
   31 |    void operator()(float** laneBuf, float** samples, int numChannels, int numSamples,
      |         ^~~~~~~~
../../Source/gui/../audio/Manta.h:31:9: note:   conversion of argument 1 would be ill-formed:
../../Source/gui/../audio/Manta.h:235:6: error: invalid conversion from ‘float* const*’ to ‘float**’ [-fpermissive]
  235 |      lane, samples, numChannels, numSamples,
      |      ^~~~
      |      |
      |      float* const*
../../Source/gui/../audio/Manta.h:247:69: error: no match for call to ‘(audio::Manta::DelayFeedback) (float* const*&, int&, int&, const int*&, const float* const&, float* const&)’
  247 |     delayFB(lane, numChannels, numSamples, wHead, rHead, feedbackBuf);
      |                                                                     ^
../../Source/gui/../audio/Manta.h:81:9: note: candidate: ‘void audio::Manta::DelayFeedback::operator()(float**, int, int, const int*, const float*, const float*)’ (near match)
   81 |    void operator()(float** samples, int numChannels, int numSamples, const int* wHead, const float* rHead,
      |         ^~~~~~~~
../../Source/gui/../audio/Manta.h:81:9: note:   conversion of argument 1 would be ill-formed:
../../Source/gui/../audio/Manta.h:247:13: error: invalid conversion from ‘float* const*’ to ‘float**’ [-fpermissive]
  247 |     delayFB(lane, numChannels, numSamples, wHead, rHead, feedbackBuf);
      |             ^~~~
      |             |
      |             float* const*
../../Source/gui/../audio/Manta.h:250:13: error: invalid conversion from ‘float* const*’ to ‘float**’ [-fpermissive]
  250 |     distort(lane, numChannels, numSamples, driveBuf);
      |             ^~~~
      |             |
      |             float* const*
../../Source/gui/../audio/Manta.h:310:25: note:   initializing argument 1 of ‘void audio::Manta::Lane::distort(float**, int, int, const float*)’
  310 |    void distort(float** samples, int numChannels, int numSamples, const float* driveBuf) noexcept
      |                 ~~~~~~~~^~~~~~~
../../Source/gui/../audio/Manta.h:256:67: error: no match for call to ‘(audio::Manta::RingMod) (float* const*&, int&, int&, float* const&, float* const&)’
  256 |     ringMod(lane, numChannels, numSamples, rmDepthBuf, rmFreqHzBuf);
      |                                                                   ^
../../Source/gui/../audio/Manta.h:133:9: note: candidate: ‘void audio::Manta::RingMod::operator()(float**, int, int, float*, float*)’ (near match)
  133 |    void operator()(float** samples, int numChannels, int numSamples,
      |         ^~~~~~~~
../../Source/gui/../audio/Manta.h:133:9: note:   conversion of argument 1 would be ill-formed:
../../Source/gui/../audio/Manta.h:256:13: error: invalid conversion from ‘float* const*’ to ‘float**’ [-fpermissive]
  256 |     ringMod(lane, numChannels, numSamples, rmDepthBuf, rmFreqHzBuf);
      |             ^~~~
      |             |
      |             float* const*
../../Source/gui/../audio/Manta.h:259:15: error: invalid conversion from ‘float* const*’ to ‘float**’ [-fpermissive]
  259 |     applyGain(lane, numChannels, numSamples, gainBuf);
      |               ^~~~
      |               |
      |               float* const*
../../Source/gui/../audio/Manta.h:321:27: note:   initializing argument 1 of ‘void audio::Manta::Lane::applyGain(float**, int, int, const float*)’
  321 |    void applyGain(float** samples, int numChannels, int numSamples, const float* gainBuf) noexcept
      |                   ~~~~~~~~^~~~~~~
Compiling MIDIVoicesComp.cpp
^Cmake: *** [Makefile:240: build/intermediate/Release/Param_89365d6c.o] Interrupt
make: *** [Makefile:255: build/intermediate/Release/FilterResponseGraph_a5957602.o] Interrupt
make: *** [Makefile:260: build/intermediate/Release/MIDICCMonitor_8dff1c06.o] Interrupt
make: *** [Makefile:265: build/intermediate/Release/MIDIVoicesComp_1d94806e.o] Interrupt

```

**Comment by tank-trax** [comment]
closing as it builds using JUCE 7.0.2

**Comment by Mrugalla** [comment]
oh yeah. sry it took me a while to answer. the problem with this is that they changed the return type of juce::AudioBuffer<Type>'s function for getting the entire buffer data from float** to float* const* and that can fuck up the project on the other implementation of juce. glad you figured it out :)
